export const GET_CINEMA_TODAY = 'GET_CINEMA_TODAY';
export const GET_FILM_BY_ID = 'GET_FILM_BY_ID';
export const GET_SCHEDULE_FILM = 'GET_SCHEDULE_FILM';
export const SET_SELECTED_SEANCE = 'SET_SELECTED_SEANCE';
export const SET_SELECTED_PLACES = 'SET_SELECTED_PLACES';